commands: # a reusable command with parameters
   deploy:
      parameters:
         ip_address:
           description: ip address of your EC2 instance
           default: "localhost"
           type: string
      steps:  
         - run:
             name: Creating the necessary package (archives)
             command: |
               sudo tar -cpjf site/joomla-data.tar.bz2 joomla-data
               sudo tar -cpjf site/db-data.tar.bz2 db-data
               realpath site
               ls -lAh site/ 

         - run:
             name: Connecting & transfering package to AWS EC2 instance...
             command:
               scp -r site/ dockeradmin@<<parameters.ip_address>>:~

         - run:
             name: Running the site on AWS EC2 instance!
             command: 
               ssh dockeradmin@<<parameters.ip_address>> "cd site/ && ./run.sh"

version: 2.1
jobs:
  Deploy_Joomla_site_on_AWS:
    docker: cimg/base:edge
    steps:
      - checkout
      - run:
          name: Where am I and Who am I?
          command: |
            pwd
            ls -lAh
            whoami
            
      - deploy:
          ip_address: "3.134.114.165"
          
workflows:
  version: 2
  my_workflow:
    jobs:
      - Deploy_Joomla_site_on_AWS
