version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run
          command: |
            echo 'Hello World!'
            echo 'This is the delivery pipeline'


