executors: # you can deploy using all of these executors;)
  docker_base_edge:
    docker:
      - image: cimg/base:edge
  docker_base_stable:
    docker:
      - image: cimg/base:stable

commands: # a reusable command with parameters
   deploy:
      parameters:
         ip_address:
           description: ip address of your EC2 instance
           default: "localhost"
           type: string
      steps:  
         - run:
             name: Preparing SSH connection for transfering package [site/]...
             command: |
               ssh-keyscan -t ecdsa <<parameters.ip_address>> >> ~/.ssh/known_hosts
               echo "~/.ssh/know_hosts"
               cat ~/.ssh/known_hosts

         - run:
             name: Transfering package [site/] to AWS EC2 instance...
             command:
               scp -r site/ dockeradmin@<<parameters.ip_address>>:~

         - run:
             name: Running the site on AWS EC2 instance!
             command: 
               ssh dockeradmin@<<parameters.ip_address>> "cd site/ && ./run.sh"

version: 2.1
jobs:
  Deploy_Joomla_site_on_AWS:
    parameters:
      exec:
        type: executor
    executor: << parameters.exec >>
    steps:
      - checkout
      - run:
          name: Where am I and Who am I?
          command: |
            pwd
            ls -lAh
            whoami
            echo "OS:"
            cat /etc/os-release
            
      - deploy:
          ip_address: "3.15.176.252"
          
workflows:
  version: 2
  my_workflow:
    jobs:
      - Deploy_Joomla_site_on_AWS:
          exec: docker_base_edge
      - Deploy_Joomla_site_on_AWS:
          exec: docker_base_stable
