executors: # you can deploy using all of these executors;)
  docker_base_edge:
    docker:
      - image: cimg/base:edge
  docker_base_stable:
    parameters:
      version:
        type: string
        default: ""
    docker:
      - image: cimg/base:stable<< parameters.version >>
  vm_ubuntu:
     machine:
      image: ubuntu-2004:202010-01

commands: # a reusable command with parameters
   deploy:
      parameters:
         ip_address:
           description: ip address of your EC2 instance
           default: "localhost"
           type: string
      steps:  
         - run:
             name: Preparing SSH connection for transfering package [site/]...
             command: |
               ssh-keyscan -t ecdsa <<parameters.ip_address>> >> ~/.ssh/known_hosts
               echo "~/.ssh/know_hosts"
               cat ~/.ssh/known_hosts

         - run:
             name: Transfering package [site/] to AWS EC2 instance...
             command:
               scp -r site/ dockeradmin@<<parameters.ip_address>>:~

         - run:
             name: Running the site on AWS EC2 instance!
             command: 
               ssh dockeradmin@<<parameters.ip_address>> "cd site/ && ./run.sh"

version: 2.1
jobs:
  Deploy_Joomla_site_on_AWS:
    parameters:
      env:
        type: executor
    executor: << parameters.env >>
    steps:
      - checkout
      - run:
          name: Where am I and Who am I?
          command: |
            pwd
            ls -lAh
            whoami
            echo "OS:"
            cat /etc/os-release
            
      - deploy:
          ip_address: "3.15.176.252"
          
workflows:
  version: 2
  my_workflow:
    jobs:
      - Deploy_Joomla_site_on_AWS:
          name: Deploy_on_docker_base_edge
          env: docker_base_edge
      - Make_approval_and_go_on!: 
          type: approval 
      - Deploy_Joomla_site_on_AWS:
          name: Deploy_on_docker_base_stable
          env: 
            name: docker_base_stable
            version: "-18.04"
      - Make_approval_and_go_on!: 
          type: approval
      - Deploy_Joomla_site_on_AWS:
          name: Deploy_on_VM_Ubuntu_2004
          env: vm_ubuntu
          
            
