version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      
      - run:
          name: Where am I?
          command: |
            pwd
            ls -lah
            whoami
  
      - run:
          name: Creating a packages (archives)
          command: |
            mkdir packages
            cd joomla-data
            sudo tar -cpjf ../packages/joomla-data.tar.bz2 .
            echo "/home/circleci/project/packages:"
            ls -l ../packages
            cd ../db-data
            pwd
            
            
            
            
