version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      
      - run:
          name: Where am I and Who am I?
          command: |
            pwd
            ls -lAh
            whoami
  
      - run:
          name: Creating the necessary package (archives)
          command: |
            mkdir site
            sudo tar -cpjf site/joomla-data.tar.bz2 joomla-data
            sudo tar -cpjf site/db-data.tar.bz2 db-data
            cp docker-compose.yml site/
            cp run.sh site/
            cp uninstall.sh site/
            realpath site
            ls -lAh site/ 

      - run:
          name: Connecting & transfering packages to AWS EC2 instance...
          command:
            scp -r site/ dockeradmin@ec2-18-216-111-124.us-east-2.compute.amazonaws.com:~

      - run
          name: Running the site AWS EC2 instance!
          command: 
            ./run.sh

