version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      
      - run:
          name: Where am I?
          command: |
            pwd
            ls -lah
            whoami
  
      - run:
          name: Creating all necessary packages (archives)
          command: |
            mkdir site
            cd joomla-data
            sudo tar -cpjf ../site/joomla-data.tar.bz2 .
            cd ../db-data
            sudo tar -cpjf ../site/db-data.tar.bz2 .
            cd ~
            pwd
            ls -lAh
            cp docker-compose.yml site/
            cp run.sh site/
            cp uninstall.sh site/
            realpath site
            ls -lAh site/ 

      - run:
          name: Connecting & transfering packages to AWS EC2 instance...
          command: |
            aws --version
            scp -r packages dockeradmin@ec2-18-216-111-124.us-east-2.compute.amazonaws.com:~

