version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      
      - run:
          name: Where am I?
          command: |
            pwd
            ls -lah
            whoami
  
      - run:
          name: Creating a packages (archives)
          command: |
            mkdir packages
            cd joomla-data
            touch joomla-data.tar.bz2
            sudo tar --exclude=joomla-data.tar.bz2 -cpjf joomla-data.tar.bz2 .
            ls -l | grep joomla-data.tar.bz2
            mv joomla-data.tar.bz2 ../packages
            ls -l ../packages
            
            
            
            
