version: 2.1

orbs:
  aws-cli: circleci/aws-cli@1.3.0

jobs:
  build:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      
      - run:
          name: Where am I?
          command: |
            pwd
            ls -lah
            whoami
  
      - run:
          name: Creating a packages (archives)
          command: |
            mkdir packages
            cd joomla-data
            sudo tar -cpjf ../packages/joomla-data.tar.bz2 .
            echo "folder 'packages':"
            ls -l ../packages
            cd ../db-data
            sudo tar -cpjf ../packages/db-data.tar.bz2 .
            echo "folder 'packages':"
            ls -l ../packages

      - run:
          name: Installing AWS-CLI
          command: |
            aws --version
            ecs-cli --version


