version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run:
          name: Where am I?
          command: |
            pwd
            ls -lah
            whoami
      - run:
          name: Creating a packages (archive)
          command: |
            cd joomla-data
            
